include classpath("application.conf")

queues {
  photo-uploads {
    defaultVisibilityTimeout = 90 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = photo-uploads-dlq
      maxReceiveCount = 3
    }
  }

  photo-uploads-dlq {}
}
