"""Add material, pattern and visual_evidence columns

Revision ID: 2975f918c5d7
Revises: d100650b8fe4
Create Date: 2026-05-03 01:00:38.571461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2975f918c5d7'
down_revision: Union[str, Sequence[str], None] = 'd100650b8fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('material', sa.String(), nullable=True))
    op.add_column('clothing_items', sa.Column('pattern', sa.String(), nullable=True))
    op.alter_column('clothing_items', 'category',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('TOP', 'BOTTOM', 'ONE_PIECE', 'OUTERWEAR', 'FOOTWEAR', 'ACTIVEWEAR', 'SWIMWEAR', 'INTIMATES', 'SLEEPWEAR', name='itemcategory', native_enum=False),
               existing_nullable=True)
    op.add_column('item_matches', sa.Column('visual_evidence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_matches', 'visual_evidence')
    op.alter_column('clothing_items', 'category',
               existing_type=sa.Enum('TOP', 'BOTTOM', 'ONE_PIECE', 'OUTERWEAR', 'FOOTWEAR', 'ACTIVEWEAR', 'SWIMWEAR', 'INTIMATES', 'SLEEPWEAR', name='itemcategory', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.drop_column('clothing_items', 'pattern')
    op.drop_column('clothing_items', 'material')
    # ### end Alembic commands ###
