"""Add core tables

Revision ID: aceea3c2fbcf
Revises: b246cda2c045
Create Date: 2026-03-21 23:47:46.697262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'aceea3c2fbcf'
down_revision: Union[str, Sequence[str], None] = 'b246cda2c045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_UPLOAD', 'PENDING_PROCESSING', 'PROCESSED', 'FAILED', name='photostatus', native_enum=False), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothing_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('closet_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'DRESS', 'OUTERWEAR', 'SHOES', 'ACCESSORY', name='itemcategory', native_enum=False), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('worn_count', sa.Integer(), nullable=True),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['closet_id'], ['closets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('clothing_item_id', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('was_confirmed', sa.Boolean(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=True),
    sa.Column('correct_item_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['correct_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tier', sa.Enum('FREE', 'PAID', name='subscriptiontier', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.drop_table('item_matches')
    op.drop_table('clothing_items')
    op.drop_table('photos')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
