"""add_file_hash_to_photos

Revision ID: d100650b8fe4
Revises: 3bb779d72703
Create Date: 2026-04-28 00:40:54.360292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd100650b8fe4'
down_revision: Union[str, Sequence[str], None] = '3bb779d72703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_photos_file_hash'), 'photos', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_file_hash'), table_name='photos')
    op.drop_column('photos', 'file_hash')
    # ### end Alembic commands ###
